### ISSUE TITLE
How to update to 2.8.x

### ISSUE THREAD

**Issue by rockingdice** [WaywardGame/mod-reference#6]
I'm modifying a mod but it seems the reference is out of date. 

BTW, which version of typescript should I use? I cannot compile with the latest version of TS.

**Comment by ChiriVulpes** [comment]
Hey @rockingdice, the way Wayward's types are installed in 2.8.x is different from 2.7.x and earlier. I recommend following [this guide](https://github.com/WaywardGame/types/wiki) in order to get set up. 

(You should just be able to navigate to the mod's folder and run `..\..\wayward.cmd +mod update .` from the console)

If you have further questions you can ask here or on the [Discord](https://discord.gg/wayward).

**Comment by rockingdice** [comment]
Thanks! I'll check it out!
